# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20161215_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='*****', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Leaders',
                'verbose_name': 'Leader',
            },
        ),
        migrations.CreateModel(
            name='LegislativeConstituency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='*****', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'LegislativeConstituencies',
                'verbose_name': 'LegislativeConstituency',
            },
        ),
        migrations.CreateModel(
            name='MemberLegislative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politics.LegislativeConstituency')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politics.Leader')),
            ],
            options={
                'verbose_name_plural': 'MemberLegislatives',
                'verbose_name': 'MemberLegislative',
            },
        ),
        migrations.CreateModel(
            name='MemberParliament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'MemberParliaments',
                'verbose_name': 'MemberParliament',
            },
        ),
        migrations.CreateModel(
            name='ParliamentConstituency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='*****', max_length=50)),
                ('lc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politics.LegislativeConstituency')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.State')),
            ],
            options={
                'verbose_name_plural': 'ParliamentConstituencies',
                'verbose_name': 'ParliamentConstituency',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(default='***', max_length=10)),
                ('full_name', models.CharField(default='*****', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Parties',
                'verbose_name': 'Party',
            },
        ),
        migrations.AddField(
            model_name='memberparliament',
            name='constituency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politics.ParliamentConstituency'),
        ),
        migrations.AddField(
            model_name='memberparliament',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politics.Leader'),
        ),
        migrations.AddField(
            model_name='legislativeconstituency',
            name='pc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politics.ParliamentConstituency'),
        ),
        migrations.AddField(
            model_name='legislativeconstituency',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.State'),
        ),
        migrations.AddField(
            model_name='leader',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politics.Party'),
        ),
    ]
