# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-13 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='author',
        ),
        migrations.RemoveField(
            model_name='pollsresponse',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='pollsresponse',
            name='user',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='PollsResponse',
        ),
    ]
