# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-24 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('house_info', models.CharField(blank=True, max_length=50)),
                ('geo_long', models.CharField(blank=True, max_length=10)),
                ('geo_lat', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50, unique=True)),
                ('password', models.CharField(default='', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('dob', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Admins',
                'verbose_name': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('area_name', models.CharField(blank=True, max_length=50)),
                ('area_pin', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'areas',
                'verbose_name': 'area',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50, unique=True)),
                ('password', models.CharField(default='', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Authors',
                'verbose_name': 'Author',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('city_name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'verbose_name': 'city',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('country_name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'verbose_name': 'country',
            },
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50, unique=True)),
                ('password', models.CharField(default='', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Moderators',
                'verbose_name': 'Moderator',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('state_name', models.CharField(blank=True, max_length=50)),
                ('fk_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Country')),
            ],
            options={
                'verbose_name_plural': 'states',
                'verbose_name': 'state',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='fk_country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='fk_state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.State'),
        ),
        migrations.AddField(
            model_name='area',
            name='fk_city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.City'),
        ),
        migrations.AddField(
            model_name='area',
            name='fk_country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Country'),
        ),
        migrations.AddField(
            model_name='area',
            name='fk_state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.State'),
        ),
        migrations.AddField(
            model_name='address',
            name='fk_area_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Area'),
        ),
    ]
